In [1]:
from __future__ import print_function
import torch

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[-8.1004e+34,  4.5644e-41, -5.0394e-23],
        [ 3.0744e-41,  3.7320e-04,  4.5644e-41],
        [ 3.7313e-04,  4.5644e-41,  3.7323e-04],
        [ 4.5644e-41,  3.7322e-04,  4.5644e-41],
        [ 3.7319e-04,  4.5644e-41,  3.7324e-04]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5106, 0.8240, 0.8922],
        [0.8289, 0.8438, 0.3027],
        [0.8100, 0.7179, 0.0695],
        [0.7183, 0.2286, 0.4859],
        [0.6867, 0.8859, 0.2045]])


In [7]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [15]:
x = x.new_ones(5, 3, dtype = torch.long)  #new_* method take in sizes
print(x)

x = torch.randn_like(x, dtype = torch.float) #overight dtype, result has the same size
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[ 0.8768, -0.3342, -0.2074],
        [ 0.8671,  0.1144, -0.9690],
        [ 1.1569, -0.7696, -1.1608],
        [ 0.0437, -0.6497, -0.2574],
        [ 0.3364,  0.3215, -0.7954]])


In [17]:
y = torch.rand(5, 3)
print(x+y)

tensor([[ 1.5170, -0.0522,  0.2177],
        [ 1.5082,  0.1531, -0.6084],
        [ 1.2482, -0.1618, -0.8698],
        [ 0.5455, -0.3868,  0.2244],
        [ 0.6260,  0.7391, -0.6402]])


In [19]:
torch.add(x, y)

tensor([[ 1.5170, -0.0522,  0.2177],
        [ 1.5082,  0.1531, -0.6084],
        [ 1.2482, -0.1618, -0.8698],
        [ 0.5455, -0.3868,  0.2244],
        [ 0.6260,  0.7391, -0.6402]])

In [21]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 1.5170, -0.0522,  0.2177],
        [ 1.5082,  0.1531, -0.6084],
        [ 1.2482, -0.1618, -0.8698],
        [ 0.5455, -0.3868,  0.2244],
        [ 0.6260,  0.7391, -0.6402]])


In [22]:
y.add_(x)
print(y)

tensor([[ 1.5170, -0.0522,  0.2177],
        [ 1.5082,  0.1531, -0.6084],
        [ 1.2482, -0.1618, -0.8698],
        [ 0.5455, -0.3868,  0.2244],
        [ 0.6260,  0.7391, -0.6402]])


In [24]:
print(x[:, 1])

tensor([-0.3342,  0.1144, -0.7696, -0.6497,  0.3215])


In [28]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [31]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.5783])
0.578313946723938


In [33]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [34]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [36]:
a.add_(1)

tensor([3., 3., 3., 3., 3.])

In [39]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
